AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda

Resources:
  MyLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: MyLambda.handler
      Runtime: python3.8
      FunctionName: "MyLambda"
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          REGION: us-east-1
